name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup docker buildx
        run: docker buildx create --name insecure-builder --buildkitd-flags "--allow-insecure-entitlement security.insecure"
      
      - name: Build container
        run: docker buildx build --progress plain  --builder insecure-builder --allow security.insecure . 